---
title: "Thesis Code"
author: "Kyle Davis"
date: "4/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path="images/")
knitr::opts_knit$set(root.dir = "~/Desktop/QMSSClasses/Spring Classes/Thesis/Datasets")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
setwd("~/Desktop/QMSSClasses/Spring Classes/Thesis/Datasets")
library(tidyverse)
library(stargazer)
```

## NCES Data Cleaning

### Read in Data

#### Setting Path Nodes
```{r}
Finance_node <- "NCES/Finance/Data"
Directory_node <- "NCES/Institutional Characteristic/Directory Information"
Fall_node <- "NCES/Institutional Characteristic/Fall Enrollment"
```

#### Read in Finance Datasets

1) Create List of all CSV files in directory
2) Initialize Dataframe by reading in first file
3) Create Year Variable to create a unique ID of UNID + year
4) Loop through all files and repeat

```{r}
final_node <- as.character(paste(getwd(),Finance_node, sep = "/")) #location of all of the csv files

finance_files <- list.files(path = final_node) #creates a list of all the files in the specified path

path <- as.character(paste(Finance_node,finance_files[[1]], sep = "/")) #1st CSV file location

finance_data <- read.csv(path) #create the dataframe

year <- str_extract_all(finance_files[[length(finance_files)]], pattern = "[0-9]{2}") #Years are specified for each file as #### where the first two numbers are last year and third/fourth number are this year.
year <- paste0("20",unlist(year)[[2]]) #set year equal to 20xx

finance_data <- finance_data %>%
  mutate(year = year) #create year variable in finance_dataset

colnames(finance_data) <- tolower(colnames(finance_data))

for(i in 2:length(finance_files)){
  path <- as.character(paste(Finance_node,finance_files[[i]], sep = "/"))
  placeholder <- read.csv(path) #create the dataframe

  year <- str_extract_all(finance_files[[i]], pattern = "[0-9]{2}")
  year <- paste0("20",unlist(year)[[2]])
  
  placeholder <- placeholder %>%
  mutate(year = year)
  
  colnames(placeholder) <- tolower(colnames(placeholder))
  finance_data <- finance_data %>%
    plyr::rbind.fill(placeholder)
}

missing_values <- finance_data %>% summarize_all(funs(sum(is.na(.))/n()))
missing_values <- gather(missing_values, key = "feature", value = "missing_pct")
missing_values %>%
  filter(missing_pct > 0.03) %>%
ggplot(aes(x=reorder(feature,-missing_pct), y = missing_pct)) +
geom_bar(stat="identity",fill="red")+
coord_flip()+theme_bw()
```

#### Selecting Relevent Variables

```{r}
varlist_path <- paste0(getwd(),"/NCES/Finance/Finance_Varlist.xlsx")
varlist <- readxl::read_xlsx(path = varlist_path, sheet = "VarList")

NCES_varnames <- c(tolower(varlist$varname), 'year')

finance_data <- finance_data %>%
  dplyr::select_(.dots = NCES_varnames)

colnames(finance_data) <- c(tolower(varlist$tidyName), 'year')

missing_values <- finance_data %>% summarize_all(funs(sum(is.na(.))/n()))
missing_values <- gather(missing_values, key = "feature", value = "missing_pct")
missing_values %>%
  filter(missing_pct > 0.03) %>%
ggplot(aes(x=reorder(feature,-missing_pct), y = missing_pct)) +
geom_bar(stat="identity",fill="red")+
coord_flip()+theme_bw()
```